//! # Migrating from v20 to v21
//!
//! 1. [`CustomAccountInterface::__check_auth`][crate::auth::CustomAccountInterface::__check_auth] function `signature_payload` parameter changes from type [`BytesN<32>`][crate::BytesN] to [`Hash<32>`][crate::crypto::Hash].
//!
//!    The two types are interchangeable. [`Hash<32>`][crate::crypto::Hash] contains a [`BytesN<32>`][crate::BytesN] and can only be constructed in contexts where the value has been generated by a secure cryptographic function.
//!
//!    Current implementations of the interface will see a build error, and should change [`BytesN<32>`][crate::BytesN] to [`Hash<32>`][crate::crypto::Hash].
//!
//!    ```
//!    use soroban_sdk::auth::CustomAccountInterface;
//!
//!    #[contract]
//!    pub struct Contract;
//!
//!    #[contractimpl]
//!    impl CustomAccountInterface for Contract {
//!        type Signature = ();
//!        type Error: Into<Error> = u32;
//!
//!        fn __check_auth(
//!            env: Env,
//!            signature_payload: Hash<32>, // 👈 👀
//!            signatures: Self::Signature,
//!            auth_contexts: Vec<Context>,
//!        ) -> Result<(), Self::Error> {
//!            // ...
//!        }
//!    }
//!    ```
//!
