version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/soroban-ledger-snapshot"
      - "/soroban-sdk-macros"
      - "/soroban-sdk"
      - "/soroban-spec-rust"
      - "/soroban-spec"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 2
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
        - "patch"
        - "minor"
      major:
        applies-to: version-updates
        update-types:
        - "major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 2
    groups:
      all-actions:
        applies-to: version-updates
        patterns: [ "*" ]