extern crate std;

use soroban_sdk::xdr::ScSpecEntry;
use std::collections::HashSet;
use std::vec::Vec;

const WASM: &[u8] = include_bytes!("../../../target/wasm32v1-none/release/test_spec_shaking.wasm");

#[test]
fn test_spec_shaking() {
    // Read all spec entries from the WASM.
    let entries = soroban_spec::read::from_wasm(WASM).unwrap();

    // Find markers embedded in the WASM data section.
    let markers = soroban_spec::shaking::find_all(WASM);

    // Filter entries using markers.
    let filtered: Vec<_> =
        soroban_spec::shaking::filter(entries.iter().cloned(), &markers).collect();

    // Collect names of filtered entries by kind for assertions.
    let filtered_names: HashSet<std::string::String> =
        filtered.iter().filter_map(entry_name).collect();

    // All functions are always kept.
    let fn_names: Vec<std::string::String> = filtered
        .iter()
        .filter_map(|e| {
            if let ScSpecEntry::FunctionV0(f) = e {
                Some(f.name.to_utf8_string_lossy())
            } else {
                None
            }
        })
        .collect();
    for expected_fn in [
        "with_param",
        "with_return",
        "with_error",
        "with_panic_error",
        "with_assert_error",
        "with_panic_raw_error",
        "with_vec",
        "with_vec_nested",
        "with_map",
        "with_recursion",
        "publish_simple",
        "publish_topic_type",
        "publish_data_type",
        "publish_nested_topic",
        "publish_nested_data",
        "publish_ref_event",
        "with_lib_struct",
        "with_wasm_imported",
        "with_option",
        "with_result",
        "with_auth_contexts",
        "with_invoker_auth",
        "with_executable",
        "with_non_pub",
        "with_non_pub_error",
        "with_tuple",
        "with_tuple_return",
    ] {
        assert!(
            fn_names.contains(&expected_fn.into()),
            "fn {expected_fn} missing"
        );
    }

    // Used types/events should be present.
    let used = [
        // fn param/return/error types
        "UsedParamStruct",
        "UsedReturnEnum",
        "UsedParamIntEnum",
        "UsedErrorEnum",
        // error types used only via panic_with_error! / assert_with_error!
        "UsedPanicErrorEnum",
        "UsedAssertErrorEnum",
        // nested in fn param struct
        "UsedNestedInStruct",
        // container element types in fn params
        "UsedVecElement",
        "UsedMapKey",
        "UsedMapVal",
        // vec element with nested custom types in data
        "UsedVecInnerVecElement",
        "UsedVecInnerElement",
        "UsedVecElementNested",
        // Option element type in fn param
        "UsedOptionElement",
        // Result Ok type in fn return
        "UsedResultOk",
        // simple event
        "UsedEventSimple",
        // event with custom type in topic
        "UsedEventTopicType",
        "UsedEventWithTopicType",
        // event with custom type in data
        "UsedEventDataType",
        "UsedEventWithDataType",
        // event with nested custom type in topic
        "UsedEventTopicOuter",
        "UsedEventTopicInner",
        "UsedEventWithNestedTopic",
        // event with nested custom type in data
        "UsedEventDataOuter",
        "UsedEventDataInner",
        "UsedEventWithNestedData",
        // event with ref fields containing custom types (topic and data with nesting)
        "UsedRefTopicType",
        "UsedRefDataType",
        "UsedRefDataInner",
        "UsedEventWithRefs",
        // tuple element types in fn params/returns
        "UsedTupleElement",
        "UsedTupleReturnElement",
        // non-pub types used as fn param/error (spec entries generated by feature)
        "UsedNonPubStruct",
        "UsedNonPubError",
        // lib-imported type used as fn param
        "StructC",
        // wasm-imported type used as fn param
        "StructA",
        // recursive type used as fn param
        "UsedRecursiveRoot",
        "UsedRecursiveNode",
        "UsedRecursiveLeaf",
        "UsedLeaf",
        // SDK internal types, which participate in normal shaking when they
        // are reachable.
        "Context",
        "ContractContext",
        "CreateContractHostFnContext",
        "CreateContractWithConstructorHostFnContext",
        "ContractExecutable",
        "ContractExecutableRef",
        "InvokerContractAuthEntry",
        "SubContractInvocation",
        "Executable",
    ];
    for name in used {
        assert!(
            filtered_names.contains(name),
            "used type/event {name} should be present in filtered entries, but was not found"
        );
    }

    // Only the entries that nothing in a spec references by name carry a
    // marker: the events the contract publishes, and the errors it panics
    // with. Every other type is named by whatever references it and is kept by
    // reachability, so the wasm carries no marker for it — including the error
    // types a function returns in a `Result`.
    let mut marked: Vec<std::string::String> = entries
        .iter()
        .filter(|e| markers.contains(&soroban_spec::shaking::generate_marker_for_entry(e)))
        .filter_map(entry_name)
        .collect();
    marked.sort();
    assert_eq!(
        marked,
        [
            // An error used only via assert_with_error!.
            "UsedAssertErrorEnum",
            // Every published event.
            "UsedEventSimple",
            "UsedEventWithDataType",
            "UsedEventWithNestedData",
            "UsedEventWithNestedTopic",
            "UsedEventWithRefs",
            "UsedEventWithTopicType",
            // An error used only via panic_with_error!.
            "UsedPanicErrorEnum",
        ]
    );
    assert_eq!(markers.len(), marked.len());

    // Unused types/events should exist in unfiltered entries: they have spec
    // entries, they are just not reachable and hold no markers.
    let unused = [
        "UnusedStruct",
        "UnusedEnum",
        "UnusedIntEnum",
        "UnusedEvent",
        // Type referenced only by an event that is never published, and so is
        // itself shaken out.
        "UnusedEventDataType",
        "UnusedEventWithDataType",
        // Types that only reference each other, reached from nowhere.
        "UnusedOuter",
        "UnusedInner",
        "UnusedPubError",
        // Types used only in non-contractimpl fns (not at contract boundary)
        "UnusedNonContractFnParam",
        "UnusedNonContractFnReturn",
        // Non-pub unused types (spec entries generated by feature, but no markers)
        "UnusedNonPubStruct",
        "UnusedNonPubError",
        // Lib-imported types not used in any contract fn (rlib statics linked into cdylib)
        "StructB",
        "StructTupleA",
        "StructTupleB",
        "StructTupleC",
        "EnumA",
        "EnumB",
        "EnumC",
        "EnumIntA",
        "EnumIntB",
        "EnumIntC",
        "ErrorA",
        "ErrorB",
        "ErrorC",
        "EventA",
        "EventB",
        "EventC",
        "EventD",
    ];
    let all_names: HashSet<std::string::String> = entries.iter().filter_map(entry_name).collect();
    for name in unused {
        assert!(
            all_names.contains(name),
            "unused type/event {name} should exist in unfiltered spec entries"
        );
    }

    // Unused types/events should be absent from filtered entries.
    for name in unused {
        assert!(
            !filtered_names.contains(name),
            "unused type/event {name} should be absent from filtered entries, but was found"
        );
    }
    assert_eq!(all_names.len() - filtered_names.len(), unused.len());
}

/// Extract the name from a non-function spec entry.
/// The simple name of the type or event the entry defines.
///
/// A user-defined type is named in the spec by its fully qualified name
/// (`mycrate::mymod::MyType`); this test asserts which types survive shaking,
/// so it names each entry by the last segment.
fn entry_name(entry: &ScSpecEntry) -> Option<std::string::String> {
    let last_segment = |name: std::string::String| -> std::string::String {
        name.rsplit("::").next().unwrap_or(&name).into()
    };
    match entry {
        ScSpecEntry::FunctionV0(_) => None,
        ScSpecEntry::UdtStructV0(s) => Some(last_segment(s.name.to_utf8_string_lossy())),
        ScSpecEntry::UdtUnionV0(u) => Some(last_segment(u.name.to_utf8_string_lossy())),
        ScSpecEntry::UdtEnumV0(e) => Some(last_segment(e.name.to_utf8_string_lossy())),
        ScSpecEntry::UdtErrorEnumV0(e) => Some(last_segment(e.name.to_utf8_string_lossy())),
        ScSpecEntry::EventV0(e) => Some(last_segment(e.name.to_utf8_string_lossy())),
    }
}
