[package]
name = "spec-json"
description = "Prints the contract spec in a wasm as a JSON array of XDR-JSON values."
version.workspace = true
edition = "2021"
rust-version.workspace = true
publish = false

[dependencies]
soroban-spec = { workspace = true }
stellar-xdr = { workspace = true, features = ["std", "serde"] }
serde_json = "1"
