//! Support for property testing Soroban contracts with [`proptest`].
//!
//! This module provides the `arb` and `arb_sized` strategies, which generate
//! the prototypes defined by the [`arbitrary`][crate::testutils::arbitrary]
//! module, and reexports the [`proptest`] crate.
//!
//! This module is only available when the "testutils-proptest" Cargo feature
//! is defined, which implies the "testutils" feature.
//!
//! [`proptest`]: https://github.com/proptest-rs/proptest/
//!
//! ```toml
//! [dev-dependencies]
//! proptest = "1"
//! soroban-sdk = { version = "*", features = ["testutils-proptest"] }
//! ```
//!
//! `arb::<T>()` generates the prototype of the Soroban type `T`. As with
//! fuzzing, prototypes are converted to contract types with [`FromVal`] or
//! [`IntoVal`], which require an [`Env`]. An `Env` cannot be carried through a
//! strategy, so the conversion happens inside the test body.
//!
//! [`Env`]: crate::Env
//! [`FromVal`]: crate::FromVal
//! [`IntoVal`]: crate::IntoVal
//! [`contracttype`]: crate::contracttype
//!
//! ```
//! use proptest::prelude::*;
//! use soroban_sdk::testutils::proptest::arb;
//! use soroban_sdk::{Address, Env, IntoVal, Vec};
//!
//! proptest! {
//!     #[test]
//!     fn test_address(address in arb::<Address>()) {
//!         let env = Env::default();
//!         let address: Address = address.into_val(&env);
//!         // test the contract with the address
//!     }
//!
//!     #[test]
//!     fn test_addresses(addresses in arb::<Vec<Address>>()) {
//!         let env = Env::default();
//!         let addresses: Vec<Address> = addresses.into_val(&env);
//!         // test the contract with the addresses
//!     }
//! }
//! ```
//!
//! The prototypes also implement [`proptest`]'s own `Arbitrary` trait, so a
//! prototype can be named directly in the parameter list instead, in the same
//! way that a fuzz test names it in its input struct. Use whichever reads
//! better: `arb` names the contract type, the parameter list names its
//! prototype.
//!
//! ```
//! use proptest::prelude::*;
//! use soroban_sdk::testutils::arbitrary::SorobanArbitrary;
//! use soroban_sdk::{Address, Env, IntoVal};
//!
//! proptest! {
//!     #[test]
//!     fn test_address(address: <Address as SorobanArbitrary>::Prototype) {
//!         let env = Env::default();
//!         let address: Address = address.into_val(&env);
//!         // test the contract with the address
//!     }
//! }
//! ```
//!
//! Types with the [`contracttype`] attribute work the same way.
//!
//! ```
//! use proptest::prelude::*;
//! use soroban_sdk::testutils::proptest::arb;
//! use soroban_sdk::{contracttype, Address, Env, IntoVal};
//!
//! #[contracttype]
//! pub struct Deposit {
//!     pub address: Address,
//!     pub amount: i128,
//! }
//!
//! proptest! {
//!     #[test]
//!     fn test_deposit(deposit in arb::<Deposit>()) {
//!         let env = Env::default();
//!         let deposit: Deposit = deposit.into_val(&env);
//!         // test the contract with the deposit
//!     }
//! }
//! ```
//!
//! ## Entropy budget
//!
//! Values are generated by feeding random bytes to the `Arbitrary`
//! implementation of the prototype, and when the bytes run out `arbitrary`
//! zero-fills the rest rather than returning an error, so too small a budget
//! produces values with a constant tail.
//!
//! The `Arbitrary` implementations take the budget from the prototype's
//! `arbitrary` size hint, which is exact for every prototype whose size is
//! bounded, including the ones `contracttype` generates. A `contracttype`
//! struct with twelve `BytesN<32>` fields is given the 384 bytes it needs.
//! Collections, strings, and `Val` have no bounded size — more bytes means
//! longer collections rather than a more complete value — so they are given a
//! 256 byte default.
//!
//! `arb` uses a fixed 256 bytes regardless of the type, so a large prototype
//! generated with it has a zeroed tail. Use `arb_sized` to raise the budget, or
//! name the prototype and let the size hint do it.
//!
//! ## Limits of generated values
//!
//! Values come from the [`Arbitrary`][::arbitrary::Arbitrary] implementations
//! of the prototypes, so the limits of those implementations apply here too —
//! collection lengths are small, and addresses are always contract addresses.
//! See the [`arbitrary`][crate::testutils::arbitrary] module docs for the
//! details.

use super::arbitrary::SorobanArbitrary;
use ::proptest::strategy::Strategy;
use core::fmt::Debug;

/// A reexport of the `proptest` crate.
pub use ::proptest;

// Used by `contracttype` to implement proptest's `Arbitrary` on the prototype it generates.
#[doc(hidden)]
pub use ::proptest_arbitrary_interop;

/// A [`proptest`] strategy that generates prototypes of the Soroban type `T`.
///
/// Prototypes are converted to their contract type with [`IntoVal`] or
/// [`FromVal`], which require an [`Env`]. Because an `Env` cannot be
/// carried through a strategy, the conversion is performed inside the test
/// body.
///
/// Values are generated by feeding random bytes to the [`Arbitrary`]
/// implementation of the prototype, with a fixed entropy budget of 256
/// bytes. A prototype that needs more bytes than that is not an error:
/// the `arbitrary` crate zero-fills the remainder, so the tail of a large
/// prototype will be all zeros in every generated value. Use
/// [`arb_sized`] with a larger budget for large types.
///
/// Collection lengths are chosen by `arbitrary`, not by proptest, and so
/// are small — see the [`arbitrary`][crate::testutils::arbitrary] module docs
/// for the distribution and how to generate larger collections.
///
/// [`proptest`]: ::proptest
/// [`Arbitrary`]: ::arbitrary::Arbitrary
/// [`Env`]: crate::Env
/// [`FromVal`]: crate::FromVal
/// [`IntoVal`]: crate::IntoVal
///
/// # Example
///
/// ```
/// use proptest::prelude::*;
/// use soroban_sdk::testutils::proptest::arb;
/// use soroban_sdk::{Address, Env, IntoVal};
///
/// proptest! {
///     #[test]
///     fn test_address(address in arb::<Address>()) {
///         let env = Env::default();
///         let address: Address = address.into_val(&env);
///         // test the contract with the address
///     }
/// }
/// ```
pub fn arb<T>() -> impl Strategy<Value = T::Prototype>
where
    T: SorobanArbitrary,
    T::Prototype: Debug + Clone + 'static,
{
    proptest_arbitrary_interop::arb::<T::Prototype>()
}

/// The same as [`arb`], but with a configurable entropy budget.
///
/// `size` is the number of random bytes fed to the [`Arbitrary`]
/// implementation of the prototype. [`arb`] uses a fixed budget of 256
/// bytes, which is not enough for large prototypes: when the bytes run out
/// `arbitrary` zero-fills the rest instead of erroring, and the tail of the
/// prototype is all zeros in every generated value. Pass a larger `size`
/// for prototypes that need more entropy, such as a contract type with
/// many `BytesN` fields.
///
/// A larger `size` also makes shrinking slower: shrinking works by
/// truncating the byte budget one byte at a time and regenerating the
/// value, so a failing case takes up to `size` steps to shrink, and the
/// counterexample reported is not necessarily minimal.
///
/// [`Arbitrary`]: ::arbitrary::Arbitrary
///
/// # Example
///
/// ```
/// use proptest::prelude::*;
/// use soroban_sdk::testutils::proptest::arb_sized;
/// use soroban_sdk::{contracttype, BytesN, Env, IntoVal};
///
/// // Twelve 32-byte fields need 384 bytes, more than the 256 bytes `arb`
/// // provides, so without a larger budget the last fields are all zeros.
/// #[contracttype]
/// pub struct Keys {
///     pub a: BytesN<32>, pub b: BytesN<32>, pub c: BytesN<32>,
///     pub d: BytesN<32>, pub e: BytesN<32>, pub f: BytesN<32>,
///     pub g: BytesN<32>, pub h: BytesN<32>, pub i: BytesN<32>,
///     pub j: BytesN<32>, pub k: BytesN<32>, pub l: BytesN<32>,
/// }
///
/// proptest! {
///     #[test]
///     fn test_keys(keys in arb_sized::<Keys>(1024)) {
///         let env = Env::default();
///         let keys: Keys = keys.into_val(&env);
///         // test the contract with the keys
///     }
/// }
/// ```
pub fn arb_sized<T>(size: usize) -> impl Strategy<Value = T::Prototype>
where
    T: SorobanArbitrary,
    T::Prototype: Debug + Clone + 'static,
{
    proptest_arbitrary_interop::arb_sized::<T::Prototype>(size)
}

/// Implementations of [`proptest`]'s `Arbitrary` trait for the prototypes.
///
/// The prototypes already implement [`arbitrary`]'s `Arbitrary`, and these
/// implementations forward to it, so that a prototype can be named directly in
/// the parameter list of a `proptest!` test, in the same way that a fuzz test
/// names it in its input struct.
///
/// The prototypes of the scalar types are the scalar types themselves, and
/// `proptest` already implements the trait for them. The prototype of a tuple
/// is a tuple of prototypes, which `proptest` covers with its own tuple
/// implementations.
///
/// The entropy budget given to a prototype whose size the `arbitrary`
/// implementation does not bound, such as a collection or a `Val`. There is no
/// size that is correct for these, because more bytes means longer collections
/// rather than a more complete value, so this is the same default that
/// `proptest-arbitrary-interop` uses.
#[doc(hidden)]
pub const UNBOUNDED_ENTROPY_BUDGET: usize = proptest_arbitrary_interop::DEFAULT_SIZE;

/// A strategy that generates the prototype `A` with an entropy budget taken
/// from its `arbitrary` implementation's size hint.
///
/// Values are generated by feeding random bytes to the `arbitrary`
/// implementation, and when the bytes run out `arbitrary` zero-fills the rest
/// instead of erroring, so a budget smaller than the prototype needs produces a
/// value with a constant tail. The size hint gives the exact number of bytes
/// for prototypes with a bounded size, which is every prototype except the
/// collections, the strings, and `Val`.
///
/// Used by the `Arbitrary` implementations below and by the ones that
/// `contracttype` generates.
#[doc(hidden)]
pub fn arb_from_size_hint<A>() -> proptest_arbitrary_interop::ArbStrategy<A>
where
    A: proptest_arbitrary_interop::ArbInterop,
{
    let (lower, upper) = <A as ::arbitrary::Arbitrary>::size_hint(0);
    let size = upper.unwrap_or(UNBOUNDED_ENTROPY_BUDGET).max(lower);
    proptest_arbitrary_interop::arb_sized::<A>(size)
}

/// [`proptest`]: https://github.com/proptest-rs/proptest/
mod prototype_impls {
    use proptest_arbitrary_interop::{ArbInterop, ArbStrategy};

    use super::arb_from_size_hint;
    use crate::testutils::arbitrary::composite::*;
    use crate::testutils::arbitrary::objects::*;

    /// Implement `proptest`'s `Arbitrary` for prototypes that have no type
    /// parameters.
    macro_rules! impl_arbitrary {
        ($($t:ty,)*) => {
            $(
                impl proptest::arbitrary::Arbitrary for $t {
                    type Parameters = ();
                    type Strategy = ArbStrategy<Self>;
                    fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
                        arb_from_size_hint::<Self>()
                    }
                }
            )*
        };
    }

    impl_arbitrary! {
        ArbitraryU256,
        ArbitraryI256,
        ArbitraryBytes,
        ArbitraryString,
        ArbitrarySymbol,
        ArbitraryAddress,
        ArbitraryMuxedAddress,
        ArbitraryTimepoint,
        ArbitraryDuration,
        ArbitraryBls12381Fp,
        ArbitraryBls12381Fp2,
        ArbitraryBls12381G1Affine,
        ArbitraryBls12381G2Affine,
        ArbitraryBls12381Fr,
        ArbitraryBn254G1Affine,
        ArbitraryBn254G2Affine,
        ArbitraryBn254Fp,
        ArbitraryBn254Fr,
        ArbitraryVal,
        ArbitraryValVec,
        ArbitraryValMap,
        ArbitraryValOption,
    }

    // The prototypes that have type parameters are implemented individually.
    // The `Self: ArbInterop` bound defers the requirements on the type
    // parameters to the prototype's `arbitrary` implementation, so that they do
    // not need restating here.

    impl<T> proptest::arbitrary::Arbitrary for ArbitraryOption<T>
    where
        Self: ArbInterop,
    {
        type Parameters = ();
        type Strategy = ArbStrategy<Self>;
        fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
            arb_from_size_hint::<Self>()
        }
    }

    impl<T> proptest::arbitrary::Arbitrary for ArbitraryVec<T>
    where
        Self: ArbInterop,
    {
        type Parameters = ();
        type Strategy = ArbStrategy<Self>;
        fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
            arb_from_size_hint::<Self>()
        }
    }

    impl<K, V> proptest::arbitrary::Arbitrary for ArbitraryMap<K, V>
    where
        Self: ArbInterop,
    {
        type Parameters = ();
        type Strategy = ArbStrategy<Self>;
        fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
            arb_from_size_hint::<Self>()
        }
    }

    impl<const N: usize> proptest::arbitrary::Arbitrary for ArbitraryBytesN<N>
    where
        Self: ArbInterop,
    {
        type Parameters = ();
        type Strategy = ArbStrategy<Self>;
        fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
            arb_from_size_hint::<Self>()
        }
    }
}
