//! Support for property testing Soroban contracts with [`proptest`].
//!
//! This module implements [`proptest`]'s `Arbitrary` trait for the prototypes
//! defined by the [`arbitrary`][crate::testutils::arbitrary] module, and
//! reexports the [`proptest`] crate. There is no strategy function to use with
//! `in`; a prototype is named in the parameter list and `proptest` finds the
//! strategy through the trait.
//!
//! This module is only available when the "testutils-proptest" Cargo feature
//! is defined, which implies the "testutils" feature.
//!
//! [`proptest`]: https://github.com/proptest-rs/proptest/
//!
//! ```toml
//! [dev-dependencies]
//! proptest = "1"
//! soroban-sdk = { version = "*", features = ["testutils-proptest"] }
//! ```
//!
//! A prototype is named in the parameter list of a `proptest!` test, in the
//! same way that a fuzz test names it in its input struct. As with fuzzing,
//! prototypes are converted to contract types with [`FromVal`] or [`IntoVal`],
//! which require an [`Env`]. An `Env` cannot be carried through a strategy, so
//! the conversion happens inside the test body.
//!
//! [`Env`]: crate::Env
//! [`FromVal`]: crate::FromVal
//! [`IntoVal`]: crate::IntoVal
//! [`contracttype`]: crate::contracttype
//!
//! ```
//! use proptest::prelude::*;
//! use soroban_sdk::testutils::arbitrary::SorobanArbitrary;
//! use soroban_sdk::{Address, Env, IntoVal, Vec};
//!
//! proptest! {
//!     #[test]
//!     fn test_address(address: <Address as SorobanArbitrary>::Prototype) {
//!         let env = Env::default();
//!         let address: Address = address.into_val(&env);
//!         // test the contract with the address
//!     }
//!
//!     #[test]
//!     fn test_addresses(addresses: <Vec<Address> as SorobanArbitrary>::Prototype) {
//!         let env = Env::default();
//!         let addresses: Vec<Address> = addresses.into_val(&env);
//!         // test the contract with the addresses
//!     }
//! }
//! ```
//!
//! Types with the [`contracttype`] attribute work the same way.
//!
//! ```
//! use proptest::prelude::*;
//! use soroban_sdk::testutils::arbitrary::SorobanArbitrary;
//! use soroban_sdk::{contracttype, Address, Env, IntoVal};
//!
//! #[contracttype]
//! pub struct Deposit {
//!     pub address: Address,
//!     pub amount: i128,
//! }
//!
//! proptest! {
//!     #[test]
//!     fn test_deposit(deposit: <Deposit as SorobanArbitrary>::Prototype) {
//!         let env = Env::default();
//!         let deposit: Deposit = deposit.into_val(&env);
//!         // test the contract with the deposit
//!     }
//! }
//! ```
//!
//! ## Entropy budget
//!
//! Values are generated by feeding random bytes to the `Arbitrary`
//! implementation of the prototype, and when the bytes run out `arbitrary`
//! zero-fills the rest rather than returning an error, so too small a budget
//! produces values with a constant tail.
//!
//! The `Arbitrary` implementations take the budget from the prototype's
//! `arbitrary` size hint, which is exact for every prototype whose size is
//! bounded, including the ones `contracttype` generates. A `contracttype`
//! struct with twelve `BytesN<32>` fields is given the 384 bytes it needs.
//! Collections, strings, and `Val` have no bounded size, so they are given a
//! budget large enough to hold a run of 16 elements of a 32 byte value. Their
//! lengths come from a coin flip before each element rather than from the bytes
//! remaining, so a larger budget does not generate longer values.
//!
//! ## Limits of generated values
//!
//! Values come from the [`Arbitrary`][::arbitrary::Arbitrary] implementations
//! of the prototypes, so the limits of those implementations apply here too —
//! collection lengths are small, and addresses are always contract addresses.
//! See the [`arbitrary`][crate::testutils::arbitrary] module docs for the
//! details.

/// A reexport of the `proptest` crate.
pub use ::proptest;

// Used by `contracttype` to implement proptest's `Arbitrary` on the prototype it generates.
#[doc(hidden)]
pub use ::proptest_arbitrary_interop;

/// The entropy budget given to a prototype whose size the `arbitrary`
/// implementation does not bound: the collections, the strings, and `Val`.
///
/// `arbitrary` decides the length of a collection with a coin flip before each
/// element, so lengths are geometrically distributed and do not grow with the
/// budget. The budget only has to be large enough not to cut that distribution
/// short, and beyond that point a larger one changes nothing. This is enough
/// for a run of 16 elements of the largest fixed size Soroban value, a 32 byte
/// `Address` or `BytesN<32>`, which the length distribution reaches about once
/// in 65536 values.
const UNBOUNDED_ENTROPY_BUDGET: usize = 16 * 32;

/// A strategy that generates the prototype `A` with an entropy budget taken
/// from its `arbitrary` implementation's size hint.
///
/// Values are generated by feeding random bytes to the `arbitrary`
/// implementation, and when the bytes run out `arbitrary` zero-fills the rest
/// instead of erroring, so a budget smaller than the prototype needs produces a
/// value with a constant tail. The size hint gives the exact number of bytes
/// for prototypes with a bounded size, which is every prototype except the
/// collections, the strings, and `Val`.
///
/// Used by the `Arbitrary` implementations below and by the ones that
/// `contracttype` generates.
#[doc(hidden)]
pub fn arb_from_size_hint<A>() -> proptest_arbitrary_interop::ArbStrategy<A>
where
    A: proptest_arbitrary_interop::ArbInterop,
{
    let (lower, upper) = <A as ::arbitrary::Arbitrary>::size_hint(0);
    let size = upper.unwrap_or(UNBOUNDED_ENTROPY_BUDGET).max(lower);
    proptest_arbitrary_interop::arb_sized::<A>(size)
}

/// [`proptest`]: https://github.com/proptest-rs/proptest/
mod prototype_impls {
    use proptest_arbitrary_interop::{ArbInterop, ArbStrategy};

    use super::arb_from_size_hint;
    use crate::testutils::arbitrary::composite::*;
    use crate::testutils::arbitrary::objects::*;

    /// Implement `proptest`'s `Arbitrary` for prototypes that have no type
    /// parameters.
    macro_rules! impl_arbitrary {
        ($($t:ty,)*) => {
            $(
                impl proptest::arbitrary::Arbitrary for $t {
                    type Parameters = ();
                    type Strategy = ArbStrategy<Self>;
                    fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
                        arb_from_size_hint::<Self>()
                    }
                }
            )*
        };
    }

    impl_arbitrary! {
        ArbitraryU256,
        ArbitraryI256,
        ArbitraryBytes,
        ArbitraryString,
        ArbitrarySymbol,
        ArbitraryAddress,
        ArbitraryMuxedAddress,
        ArbitraryTimepoint,
        ArbitraryDuration,
        ArbitraryBls12381Fp,
        ArbitraryBls12381Fp2,
        ArbitraryBls12381G1Affine,
        ArbitraryBls12381G2Affine,
        ArbitraryBls12381Fr,
        ArbitraryBn254G1Affine,
        ArbitraryBn254G2Affine,
        ArbitraryBn254Fp,
        ArbitraryBn254Fr,
        ArbitraryVal,
        ArbitraryValVec,
        ArbitraryValMap,
        ArbitraryValOption,
    }

    // The prototypes that have type parameters are implemented individually.
    // The `Self: ArbInterop` bound defers the requirements on the type
    // parameters to the prototype's `arbitrary` implementation, so that they do
    // not need restating here.

    impl<T> proptest::arbitrary::Arbitrary for ArbitraryOption<T>
    where
        Self: ArbInterop,
    {
        type Parameters = ();
        type Strategy = ArbStrategy<Self>;
        fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
            arb_from_size_hint::<Self>()
        }
    }

    impl<T> proptest::arbitrary::Arbitrary for ArbitraryVec<T>
    where
        Self: ArbInterop,
    {
        type Parameters = ();
        type Strategy = ArbStrategy<Self>;
        fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
            arb_from_size_hint::<Self>()
        }
    }

    impl<K, V> proptest::arbitrary::Arbitrary for ArbitraryMap<K, V>
    where
        Self: ArbInterop,
    {
        type Parameters = ();
        type Strategy = ArbStrategy<Self>;
        fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
            arb_from_size_hint::<Self>()
        }
    }

    impl<const N: usize> proptest::arbitrary::Arbitrary for ArbitraryBytesN<N>
    where
        Self: ArbInterop,
    {
        type Parameters = ();
        type Strategy = ArbStrategy<Self>;
        fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
            arb_from_size_hint::<Self>()
        }
    }
}
