[package]
name = "test_contracttrait_crate_path"
version.workspace = true
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
edition = "2021"
publish = false
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
sdk = {package = "soroban-sdk", path = "../../soroban-sdk"}

[dev-dependencies]
sdk = {package = "soroban-sdk", path = "../../soroban-sdk", features = ["testutils"]}
