[package]
name = "test_spec_shaking_v3"
version.workspace = true
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
edition = "2021"
publish = false
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = {path = "../../soroban-sdk"}
test_spec_lib = {package = "test_spec_lib_v3", path = "../spec_lib_v3"}

[dev-dependencies]
soroban-sdk = {path = "../../soroban-sdk", features = ["testutils"]}
stellar-xdr = {workspace = true, features = ["std"]}
soroban-spec = {path = "../../soroban-spec"}
soroban-meta = {path = "../../soroban-meta"}
