use soroban_sdk::{contractevent, contracttype};

// A type's name in the spec is its module path followed by its own name, so a
// long enough module path takes the name past the spec's type name limit.

pub mod long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_end {
    use super::*;

    #[contracttype]
    pub struct TooLong {
        pub val: u32,
    }

    #[contractevent]
    pub struct TooLongEvent {
        pub val: u32,
    }
}

// A type that refers to a type whose name is too long adds no further error.
#[contracttype]
pub struct Refers {
    pub val: long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_long_module_name_end::TooLong,
}

fn main() {}
