[package]
name = "example_vec_iter"
version = "0.0.0"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
stellar-contract-sdk = {path = "../../sdk"}

[dev-dependencies]
proptest = "1.0.0"
