//! IncludeSpecMarker is an internal trait used to ensure that contract type specs
//! are included in the WASM binary when types are used at contract boundaries.
//!
//! The trait is called at three external boundary points:
//! 1. Contract function input parameters
//! 2. Contract function return values
//! 3. Event publishing
//!
//! Types that are only used internally (storage, cross-contract calls) do not
//! need their specs included, so the trait is NOT called from general TryFromVal
//! conversions.
//!
//! The trait has a default no-op implementation. Types generated by contracttype,
//! contractevent, and contracterror macros implement this trait to include their
//! spec XDR in the WASM's contractspecv0 section.

/// Trait for types that may include their spec in the WASM binary.
///
/// This trait is used internally by the SDK to ensure contract type specs
/// are included when types are used at external boundaries (function params,
/// return values, events).
///
/// Types with `#[contracttype]`, `#[contractevent]`, or `#[contracterror]`
/// will have implementations that include their spec. All other types have
/// a no-op implementation.
#[doc(hidden)]
pub trait IncludeSpecMarker {
    /// Include this type's spec in the WASM binary.
    ///
    /// For primitive types and built-in SDK types, this is a no-op.
    /// For user-defined contract types, this ensures the spec XDR is
    /// included in the contractspecv0 section.
    #[inline(always)]
    fn include_spec_marker() {}
}

// Primitive type implementations (no-op)
impl IncludeSpecMarker for () {}
impl IncludeSpecMarker for bool {}
impl IncludeSpecMarker for u32 {}
impl IncludeSpecMarker for i32 {}
impl IncludeSpecMarker for u64 {}
impl IncludeSpecMarker for i64 {}
impl IncludeSpecMarker for u128 {}
impl IncludeSpecMarker for i128 {}

// Reference implementations
impl<T: IncludeSpecMarker> IncludeSpecMarker for &T {
    #[inline(always)]
    fn include_spec_marker() {
        T::include_spec_marker();
    }
}

impl<T: IncludeSpecMarker> IncludeSpecMarker for &mut T {
    #[inline(always)]
    fn include_spec_marker() {
        T::include_spec_marker();
    }
}

// Option implementation - includes inner type's spec
impl<T: IncludeSpecMarker> IncludeSpecMarker for Option<T> {
    #[inline(always)]
    fn include_spec_marker() {
        T::include_spec_marker();
    }
}

// Result implementation - includes both type's specs
impl<T: IncludeSpecMarker, E: IncludeSpecMarker> IncludeSpecMarker for Result<T, E> {
    #[inline(always)]
    fn include_spec_marker() {
        T::include_spec_marker();
        E::include_spec_marker();
    }
}

// Tuple implementations
impl<T0: IncludeSpecMarker> IncludeSpecMarker for (T0,) {
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
    }
}

impl<T0: IncludeSpecMarker, T1: IncludeSpecMarker> IncludeSpecMarker for (T0, T1) {
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
    }
}

impl<T0: IncludeSpecMarker, T1: IncludeSpecMarker, T2: IncludeSpecMarker> IncludeSpecMarker
    for (T0, T1, T2)
{
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
        T2::include_spec_marker();
    }
}

impl<
        T0: IncludeSpecMarker,
        T1: IncludeSpecMarker,
        T2: IncludeSpecMarker,
        T3: IncludeSpecMarker,
    > IncludeSpecMarker for (T0, T1, T2, T3)
{
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
        T2::include_spec_marker();
        T3::include_spec_marker();
    }
}

impl<
        T0: IncludeSpecMarker,
        T1: IncludeSpecMarker,
        T2: IncludeSpecMarker,
        T3: IncludeSpecMarker,
        T4: IncludeSpecMarker,
    > IncludeSpecMarker for (T0, T1, T2, T3, T4)
{
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
        T2::include_spec_marker();
        T3::include_spec_marker();
        T4::include_spec_marker();
    }
}

impl<
        T0: IncludeSpecMarker,
        T1: IncludeSpecMarker,
        T2: IncludeSpecMarker,
        T3: IncludeSpecMarker,
        T4: IncludeSpecMarker,
        T5: IncludeSpecMarker,
    > IncludeSpecMarker for (T0, T1, T2, T3, T4, T5)
{
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
        T2::include_spec_marker();
        T3::include_spec_marker();
        T4::include_spec_marker();
        T5::include_spec_marker();
    }
}

impl<
        T0: IncludeSpecMarker,
        T1: IncludeSpecMarker,
        T2: IncludeSpecMarker,
        T3: IncludeSpecMarker,
        T4: IncludeSpecMarker,
        T5: IncludeSpecMarker,
        T6: IncludeSpecMarker,
    > IncludeSpecMarker for (T0, T1, T2, T3, T4, T5, T6)
{
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
        T2::include_spec_marker();
        T3::include_spec_marker();
        T4::include_spec_marker();
        T5::include_spec_marker();
        T6::include_spec_marker();
    }
}

impl<
        T0: IncludeSpecMarker,
        T1: IncludeSpecMarker,
        T2: IncludeSpecMarker,
        T3: IncludeSpecMarker,
        T4: IncludeSpecMarker,
        T5: IncludeSpecMarker,
        T6: IncludeSpecMarker,
        T7: IncludeSpecMarker,
    > IncludeSpecMarker for (T0, T1, T2, T3, T4, T5, T6, T7)
{
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
        T2::include_spec_marker();
        T3::include_spec_marker();
        T4::include_spec_marker();
        T5::include_spec_marker();
        T6::include_spec_marker();
        T7::include_spec_marker();
    }
}

impl<
        T0: IncludeSpecMarker,
        T1: IncludeSpecMarker,
        T2: IncludeSpecMarker,
        T3: IncludeSpecMarker,
        T4: IncludeSpecMarker,
        T5: IncludeSpecMarker,
        T6: IncludeSpecMarker,
        T7: IncludeSpecMarker,
        T8: IncludeSpecMarker,
    > IncludeSpecMarker for (T0, T1, T2, T3, T4, T5, T6, T7, T8)
{
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
        T2::include_spec_marker();
        T3::include_spec_marker();
        T4::include_spec_marker();
        T5::include_spec_marker();
        T6::include_spec_marker();
        T7::include_spec_marker();
        T8::include_spec_marker();
    }
}

impl<
        T0: IncludeSpecMarker,
        T1: IncludeSpecMarker,
        T2: IncludeSpecMarker,
        T3: IncludeSpecMarker,
        T4: IncludeSpecMarker,
        T5: IncludeSpecMarker,
        T6: IncludeSpecMarker,
        T7: IncludeSpecMarker,
        T8: IncludeSpecMarker,
        T9: IncludeSpecMarker,
    > IncludeSpecMarker for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9)
{
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
        T2::include_spec_marker();
        T3::include_spec_marker();
        T4::include_spec_marker();
        T5::include_spec_marker();
        T6::include_spec_marker();
        T7::include_spec_marker();
        T8::include_spec_marker();
        T9::include_spec_marker();
    }
}

impl<
        T0: IncludeSpecMarker,
        T1: IncludeSpecMarker,
        T2: IncludeSpecMarker,
        T3: IncludeSpecMarker,
        T4: IncludeSpecMarker,
        T5: IncludeSpecMarker,
        T6: IncludeSpecMarker,
        T7: IncludeSpecMarker,
        T8: IncludeSpecMarker,
        T9: IncludeSpecMarker,
        T10: IncludeSpecMarker,
    > IncludeSpecMarker for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)
{
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
        T2::include_spec_marker();
        T3::include_spec_marker();
        T4::include_spec_marker();
        T5::include_spec_marker();
        T6::include_spec_marker();
        T7::include_spec_marker();
        T8::include_spec_marker();
        T9::include_spec_marker();
        T10::include_spec_marker();
    }
}

impl<
        T0: IncludeSpecMarker,
        T1: IncludeSpecMarker,
        T2: IncludeSpecMarker,
        T3: IncludeSpecMarker,
        T4: IncludeSpecMarker,
        T5: IncludeSpecMarker,
        T6: IncludeSpecMarker,
        T7: IncludeSpecMarker,
        T8: IncludeSpecMarker,
        T9: IncludeSpecMarker,
        T10: IncludeSpecMarker,
        T11: IncludeSpecMarker,
    > IncludeSpecMarker for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)
{
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
        T2::include_spec_marker();
        T3::include_spec_marker();
        T4::include_spec_marker();
        T5::include_spec_marker();
        T6::include_spec_marker();
        T7::include_spec_marker();
        T8::include_spec_marker();
        T9::include_spec_marker();
        T10::include_spec_marker();
        T11::include_spec_marker();
    }
}

impl<
        T0: IncludeSpecMarker,
        T1: IncludeSpecMarker,
        T2: IncludeSpecMarker,
        T3: IncludeSpecMarker,
        T4: IncludeSpecMarker,
        T5: IncludeSpecMarker,
        T6: IncludeSpecMarker,
        T7: IncludeSpecMarker,
        T8: IncludeSpecMarker,
        T9: IncludeSpecMarker,
        T10: IncludeSpecMarker,
        T11: IncludeSpecMarker,
        T12: IncludeSpecMarker,
    > IncludeSpecMarker for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)
{
    #[inline(always)]
    fn include_spec_marker() {
        T0::include_spec_marker();
        T1::include_spec_marker();
        T2::include_spec_marker();
        T3::include_spec_marker();
        T4::include_spec_marker();
        T5::include_spec_marker();
        T6::include_spec_marker();
        T7::include_spec_marker();
        T8::include_spec_marker();
        T9::include_spec_marker();
        T10::include_spec_marker();
        T11::include_spec_marker();
        T12::include_spec_marker();
    }
}

// SDK type implementations (no-op for built-in types, propagate for containers)
// These are imported via crate:: to avoid circular dependencies

impl IncludeSpecMarker for crate::Address {}
impl IncludeSpecMarker for crate::Bytes {}
impl<const N: usize> IncludeSpecMarker for crate::BytesN<N> {}
impl IncludeSpecMarker for crate::String {}
impl IncludeSpecMarker for crate::Symbol {}
impl IncludeSpecMarker for crate::U256 {}
impl IncludeSpecMarker for crate::I256 {}
impl IncludeSpecMarker for crate::Timepoint {}
impl IncludeSpecMarker for crate::Duration {}
impl IncludeSpecMarker for crate::Val {}

// Container types - propagate to inner types
impl<T: IncludeSpecMarker> IncludeSpecMarker for crate::Vec<T> {
    #[inline(always)]
    fn include_spec_marker() {
        T::include_spec_marker();
    }
}

impl<K: IncludeSpecMarker, V: IncludeSpecMarker> IncludeSpecMarker for crate::Map<K, V> {
    #[inline(always)]
    fn include_spec_marker() {
        K::include_spec_marker();
        V::include_spec_marker();
    }
}

// Additional SDK types
impl IncludeSpecMarker for crate::MuxedAddress {}
impl<const N: usize> IncludeSpecMarker for crate::crypto::Hash<N> {}
impl IncludeSpecMarker for crate::crypto::bls12_381::G1Affine {}
impl IncludeSpecMarker for crate::crypto::bls12_381::G2Affine {}
impl IncludeSpecMarker for crate::crypto::bls12_381::Fp {}
impl IncludeSpecMarker for crate::crypto::bls12_381::Fp2 {}
impl IncludeSpecMarker for crate::crypto::bls12_381::Fr {}
impl IncludeSpecMarker for crate::crypto::bn254::Bn254G1Affine {}
impl IncludeSpecMarker for crate::crypto::bn254::Bn254G2Affine {}
impl IncludeSpecMarker for crate::crypto::bn254::Bn254Fp {}
impl IncludeSpecMarker for crate::crypto::bn254::Fr {}

// Auth types - these have export=false but are legitimately used at external
// boundaries (as inputs to __check_auth in custom account contracts).
// They don't emit specs themselves because they're internal SDK types.
impl IncludeSpecMarker for crate::auth::Context {}
impl IncludeSpecMarker for crate::auth::ContractContext {}
impl IncludeSpecMarker for crate::auth::CreateContractHostFnContext {}
impl IncludeSpecMarker for crate::auth::CreateContractWithConstructorHostFnContext {}
impl IncludeSpecMarker for crate::auth::ContractExecutable {}
impl IncludeSpecMarker for crate::auth::InvokerContractAuthEntry {}
impl IncludeSpecMarker for crate::auth::SubContractInvocation {}
