//! IncludeSpec is an internal trait used to ensure that contract type specs
//! are included in the WASM binary when types are used at contract boundaries.
//!
//! The trait is called at three external boundary points:
//! 1. Contract function input parameters
//! 2. Contract function return values
//! 3. Event publishing
//!
//! Types that are only used internally (storage, cross-contract calls) do not
//! need their specs included, so the trait is NOT called from general TryFromVal
//! conversions.
//!
//! The trait has a default no-op implementation. Types generated by contracttype,
//! contractevent, and contracterror macros implement this trait to include their
//! spec XDR in the WASM's contractspecv0 section.

/// Trait for types that may include their spec in the WASM binary.
///
/// This trait is used internally by the SDK to ensure contract type specs
/// are included when types are used at external boundaries (function params,
/// return values, events).
///
/// Types with `#[contracttype]`, `#[contractevent]`, or `#[contracterror]`
/// will have implementations that include their spec. All other types have
/// a no-op implementation.
#[doc(hidden)]
pub trait IncludeSpec {
    /// Include this type's spec in the WASM binary.
    ///
    /// For primitive types and built-in SDK types, this is a no-op.
    /// For user-defined contract types, this ensures the spec XDR is
    /// included in the contractspecv0 section.
    #[inline(always)]
    fn __include_spec() {}
}

// Primitive type implementations (no-op)
impl IncludeSpec for () {}
impl IncludeSpec for bool {}
impl IncludeSpec for u32 {}
impl IncludeSpec for i32 {}
impl IncludeSpec for u64 {}
impl IncludeSpec for i64 {}
impl IncludeSpec for u128 {}
impl IncludeSpec for i128 {}

// Reference implementations
impl<T: IncludeSpec> IncludeSpec for &T {
    #[inline(always)]
    fn __include_spec() {
        T::__include_spec();
    }
}

impl<T: IncludeSpec> IncludeSpec for &mut T {
    #[inline(always)]
    fn __include_spec() {
        T::__include_spec();
    }
}

// Option implementation - includes inner type's spec
impl<T: IncludeSpec> IncludeSpec for Option<T> {
    #[inline(always)]
    fn __include_spec() {
        T::__include_spec();
    }
}

// Result implementation - includes both type's specs
impl<T: IncludeSpec, E: IncludeSpec> IncludeSpec for Result<T, E> {
    #[inline(always)]
    fn __include_spec() {
        T::__include_spec();
        E::__include_spec();
    }
}

// Tuple implementations
impl<T0: IncludeSpec> IncludeSpec for (T0,) {
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
    }
}

impl<T0: IncludeSpec, T1: IncludeSpec> IncludeSpec for (T0, T1) {
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
    }
}

impl<T0: IncludeSpec, T1: IncludeSpec, T2: IncludeSpec> IncludeSpec for (T0, T1, T2) {
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
        T2::__include_spec();
    }
}

impl<T0: IncludeSpec, T1: IncludeSpec, T2: IncludeSpec, T3: IncludeSpec> IncludeSpec
    for (T0, T1, T2, T3)
{
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
        T2::__include_spec();
        T3::__include_spec();
    }
}

impl<T0: IncludeSpec, T1: IncludeSpec, T2: IncludeSpec, T3: IncludeSpec, T4: IncludeSpec>
    IncludeSpec for (T0, T1, T2, T3, T4)
{
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
        T2::__include_spec();
        T3::__include_spec();
        T4::__include_spec();
    }
}

impl<
        T0: IncludeSpec,
        T1: IncludeSpec,
        T2: IncludeSpec,
        T3: IncludeSpec,
        T4: IncludeSpec,
        T5: IncludeSpec,
    > IncludeSpec for (T0, T1, T2, T3, T4, T5)
{
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
        T2::__include_spec();
        T3::__include_spec();
        T4::__include_spec();
        T5::__include_spec();
    }
}

impl<
        T0: IncludeSpec,
        T1: IncludeSpec,
        T2: IncludeSpec,
        T3: IncludeSpec,
        T4: IncludeSpec,
        T5: IncludeSpec,
        T6: IncludeSpec,
    > IncludeSpec for (T0, T1, T2, T3, T4, T5, T6)
{
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
        T2::__include_spec();
        T3::__include_spec();
        T4::__include_spec();
        T5::__include_spec();
        T6::__include_spec();
    }
}

impl<
        T0: IncludeSpec,
        T1: IncludeSpec,
        T2: IncludeSpec,
        T3: IncludeSpec,
        T4: IncludeSpec,
        T5: IncludeSpec,
        T6: IncludeSpec,
        T7: IncludeSpec,
    > IncludeSpec for (T0, T1, T2, T3, T4, T5, T6, T7)
{
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
        T2::__include_spec();
        T3::__include_spec();
        T4::__include_spec();
        T5::__include_spec();
        T6::__include_spec();
        T7::__include_spec();
    }
}

impl<
        T0: IncludeSpec,
        T1: IncludeSpec,
        T2: IncludeSpec,
        T3: IncludeSpec,
        T4: IncludeSpec,
        T5: IncludeSpec,
        T6: IncludeSpec,
        T7: IncludeSpec,
        T8: IncludeSpec,
    > IncludeSpec for (T0, T1, T2, T3, T4, T5, T6, T7, T8)
{
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
        T2::__include_spec();
        T3::__include_spec();
        T4::__include_spec();
        T5::__include_spec();
        T6::__include_spec();
        T7::__include_spec();
        T8::__include_spec();
    }
}

impl<
        T0: IncludeSpec,
        T1: IncludeSpec,
        T2: IncludeSpec,
        T3: IncludeSpec,
        T4: IncludeSpec,
        T5: IncludeSpec,
        T6: IncludeSpec,
        T7: IncludeSpec,
        T8: IncludeSpec,
        T9: IncludeSpec,
    > IncludeSpec for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9)
{
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
        T2::__include_spec();
        T3::__include_spec();
        T4::__include_spec();
        T5::__include_spec();
        T6::__include_spec();
        T7::__include_spec();
        T8::__include_spec();
        T9::__include_spec();
    }
}

impl<
        T0: IncludeSpec,
        T1: IncludeSpec,
        T2: IncludeSpec,
        T3: IncludeSpec,
        T4: IncludeSpec,
        T5: IncludeSpec,
        T6: IncludeSpec,
        T7: IncludeSpec,
        T8: IncludeSpec,
        T9: IncludeSpec,
        T10: IncludeSpec,
    > IncludeSpec for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)
{
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
        T2::__include_spec();
        T3::__include_spec();
        T4::__include_spec();
        T5::__include_spec();
        T6::__include_spec();
        T7::__include_spec();
        T8::__include_spec();
        T9::__include_spec();
        T10::__include_spec();
    }
}

impl<
        T0: IncludeSpec,
        T1: IncludeSpec,
        T2: IncludeSpec,
        T3: IncludeSpec,
        T4: IncludeSpec,
        T5: IncludeSpec,
        T6: IncludeSpec,
        T7: IncludeSpec,
        T8: IncludeSpec,
        T9: IncludeSpec,
        T10: IncludeSpec,
        T11: IncludeSpec,
    > IncludeSpec for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)
{
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
        T2::__include_spec();
        T3::__include_spec();
        T4::__include_spec();
        T5::__include_spec();
        T6::__include_spec();
        T7::__include_spec();
        T8::__include_spec();
        T9::__include_spec();
        T10::__include_spec();
        T11::__include_spec();
    }
}

impl<
        T0: IncludeSpec,
        T1: IncludeSpec,
        T2: IncludeSpec,
        T3: IncludeSpec,
        T4: IncludeSpec,
        T5: IncludeSpec,
        T6: IncludeSpec,
        T7: IncludeSpec,
        T8: IncludeSpec,
        T9: IncludeSpec,
        T10: IncludeSpec,
        T11: IncludeSpec,
        T12: IncludeSpec,
    > IncludeSpec for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)
{
    #[inline(always)]
    fn __include_spec() {
        T0::__include_spec();
        T1::__include_spec();
        T2::__include_spec();
        T3::__include_spec();
        T4::__include_spec();
        T5::__include_spec();
        T6::__include_spec();
        T7::__include_spec();
        T8::__include_spec();
        T9::__include_spec();
        T10::__include_spec();
        T11::__include_spec();
        T12::__include_spec();
    }
}

// SDK type implementations (no-op for built-in types, propagate for containers)
// These are imported via crate:: to avoid circular dependencies

impl IncludeSpec for crate::Address {}
impl IncludeSpec for crate::Bytes {}
impl<const N: usize> IncludeSpec for crate::BytesN<N> {}
impl IncludeSpec for crate::String {}
impl IncludeSpec for crate::Symbol {}
impl IncludeSpec for crate::U256 {}
impl IncludeSpec for crate::I256 {}
impl IncludeSpec for crate::Timepoint {}
impl IncludeSpec for crate::Duration {}
impl IncludeSpec for crate::Val {}

// Container types - propagate to inner types
impl<T: IncludeSpec> IncludeSpec for crate::Vec<T> {
    #[inline(always)]
    fn __include_spec() {
        T::__include_spec();
    }
}

impl<K: IncludeSpec, V: IncludeSpec> IncludeSpec for crate::Map<K, V> {
    #[inline(always)]
    fn __include_spec() {
        K::__include_spec();
        V::__include_spec();
    }
}

// Additional SDK types
impl IncludeSpec for crate::MuxedAddress {}
impl<const N: usize> IncludeSpec for crate::crypto::Hash<N> {}
impl IncludeSpec for crate::crypto::bls12_381::G1Affine {}
impl IncludeSpec for crate::crypto::bls12_381::G2Affine {}
impl IncludeSpec for crate::crypto::bls12_381::Fp {}
impl IncludeSpec for crate::crypto::bls12_381::Fp2 {}
impl IncludeSpec for crate::crypto::bls12_381::Fr {}

// Auth types - these have export=false but are legitimately used at external
// boundaries (as inputs to __check_auth in custom account contracts).
// They don't emit specs themselves because they're internal SDK types.
impl IncludeSpec for crate::auth::Context {}
impl IncludeSpec for crate::auth::ContractContext {}
impl IncludeSpec for crate::auth::CreateContractHostFnContext {}
impl IncludeSpec for crate::auth::CreateContractWithConstructorHostFnContext {}
impl IncludeSpec for crate::auth::ContractExecutable {}
impl IncludeSpec for crate::auth::InvokerContractAuthEntry {}
impl IncludeSpec for crate::auth::SubContractInvocation {}
