//! SpecShakingMarker is an internal trait used to ensure that contract type
//! specs are included in the WASM binary when types are used at contract
//! boundaries.
//!
//! The trait is consulted at three external boundary points:
//! 1. Contract function input parameters
//! 2. Contract function return values
//! 3. Event publishing
//!
//! Types that are only used internally (storage, cross-contract calls) do not
//! need their specs included, so the trait is NOT called from general TryFromVal
//! conversions.
//!
//! Every type that implements the trait exposes a `*const MarkerNode` via the
//! associated `MARKER_NODE` const. Nodes form a static graph via their
//! `children` slice. At the contract-fn boundary, a single `read_volatile` on a
//! pointer to the root `MARKER_NODE` roots the graph; rustc/LLVM and the WASM
//! linker then keep every transitively-referenced node (and its 14-byte
//! `SpEcV1…` marker bytes) alive through dead-code elimination. Types that
//! aren't reached from any boundary get DCE'd along with their markers, which
//! is the signal the post-build tool uses to decide which `contractspecv0`
//! entries to strip.
//!
//! Cycles in the type graph (e.g. `struct S { v: Vec<S> }`) are handled
//! natively. Children are stored as raw `*const MarkerNode` rather than
//! `&'static MarkerNode` specifically to break rustc's const-evaluation
//! cycle detector: evaluating a `&'static X` reference in a `const` expression
//! triggers evaluation of `X`'s initializer, but evaluating a `*const X`
//! (produced by either `&raw const X` on a named static or `&X {…} as *const X`
//! on a promoted static) does not. At link time, both forms resolve to the
//! same data-section addresses.

/// A node in the spec-shaking reachability graph.
///
/// Every `SpecShakingMarker` impl returns a `*const MarkerNode`. The
/// `marker` field holds the 14-byte `SpEcV1…` marker for types that have a
/// spec entry (user types generated by `#[contracttype]`/`#[contractevent]`/
/// `#[contracterror]`); it is all-zero for nodes that exist only to propagate
/// reachability to child types (containers, references, primitives).
#[doc(hidden)]
#[repr(C)]
pub struct MarkerNode {
    pub marker: [u8; 14],
    pub children: &'static [*const MarkerNode],
}

// MarkerNode contains raw pointers which aren't `Sync` by default. Safe here
// because the pointers are never dereferenced at runtime — they exist purely
// to keep statics reachable through linker DCE. The data is also immutable.
#[doc(hidden)]
unsafe impl Sync for MarkerNode {}

/// Shared sentinel for primitives and other types that carry no spec entry
/// and have no children. One static, referenced from many impls.
#[doc(hidden)]
pub static EMPTY_MARKER_NODE: MarkerNode = MarkerNode {
    marker: [0u8; 14],
    children: &[],
};

/// Trait for types that may include their spec in the WASM binary.
///
/// This trait is used internally by the SDK to ensure contract type specs
/// are included when types are used at external boundaries (function params,
/// return values, events).
///
/// Types with `#[contracttype]`, `#[contractevent]`, or `#[contracterror]`
/// implement this by emitting a `MarkerNode` containing their own 14-byte
/// marker and pointers to child types' nodes. All other types (primitives,
/// built-in SDK types, containers) also implement the trait with the same
/// shape — primitives and empty containers share [`EMPTY_MARKER_NODE`]; non-
/// empty containers emit a wrapper node pointing at their element type(s).
#[doc(hidden)]
pub trait SpecShakingMarker {
    const MARKER_NODE: *const MarkerNode;
}

// --- Primitive type implementations -----------------------------------------

impl SpecShakingMarker for () {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for bool {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for u32 {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for i32 {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for u64 {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for i64 {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for u128 {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for i128 {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}

// --- Reference implementations ----------------------------------------------
//
// References carry no spec of their own, so they forward directly to the
// inner type's MARKER_NODE rather than emit a wrapper node.

impl<T: SpecShakingMarker> SpecShakingMarker for &T {
    const MARKER_NODE: *const MarkerNode = T::MARKER_NODE;
}

impl<T: SpecShakingMarker> SpecShakingMarker for &mut T {
    const MARKER_NODE: *const MarkerNode = T::MARKER_NODE;
}

// --- Option / Result --------------------------------------------------------

impl<T: SpecShakingMarker> SpecShakingMarker for Option<T> {
    // Single-child: forward directly, no wrapper node.
    const MARKER_NODE: *const MarkerNode = T::MARKER_NODE;
}

impl<T: SpecShakingMarker, E: SpecShakingMarker> SpecShakingMarker for Result<T, E> {
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[T::MARKER_NODE, E::MARKER_NODE],
    } as *const MarkerNode;
}

// --- Tuple implementations --------------------------------------------------

impl<T0: SpecShakingMarker> SpecShakingMarker for (T0,) {
    const MARKER_NODE: *const MarkerNode = T0::MARKER_NODE;
}

impl<T0: SpecShakingMarker, T1: SpecShakingMarker> SpecShakingMarker for (T0, T1) {
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[T0::MARKER_NODE, T1::MARKER_NODE],
    } as *const MarkerNode;
}

impl<T0: SpecShakingMarker, T1: SpecShakingMarker, T2: SpecShakingMarker> SpecShakingMarker
    for (T0, T1, T2)
{
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[T0::MARKER_NODE, T1::MARKER_NODE, T2::MARKER_NODE],
    } as *const MarkerNode;
}

impl<
        T0: SpecShakingMarker,
        T1: SpecShakingMarker,
        T2: SpecShakingMarker,
        T3: SpecShakingMarker,
    > SpecShakingMarker for (T0, T1, T2, T3)
{
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[
            T0::MARKER_NODE,
            T1::MARKER_NODE,
            T2::MARKER_NODE,
            T3::MARKER_NODE,
        ],
    } as *const MarkerNode;
}

impl<
        T0: SpecShakingMarker,
        T1: SpecShakingMarker,
        T2: SpecShakingMarker,
        T3: SpecShakingMarker,
        T4: SpecShakingMarker,
    > SpecShakingMarker for (T0, T1, T2, T3, T4)
{
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[
            T0::MARKER_NODE,
            T1::MARKER_NODE,
            T2::MARKER_NODE,
            T3::MARKER_NODE,
            T4::MARKER_NODE,
        ],
    } as *const MarkerNode;
}

impl<
        T0: SpecShakingMarker,
        T1: SpecShakingMarker,
        T2: SpecShakingMarker,
        T3: SpecShakingMarker,
        T4: SpecShakingMarker,
        T5: SpecShakingMarker,
    > SpecShakingMarker for (T0, T1, T2, T3, T4, T5)
{
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[
            T0::MARKER_NODE,
            T1::MARKER_NODE,
            T2::MARKER_NODE,
            T3::MARKER_NODE,
            T4::MARKER_NODE,
            T5::MARKER_NODE,
        ],
    } as *const MarkerNode;
}

impl<
        T0: SpecShakingMarker,
        T1: SpecShakingMarker,
        T2: SpecShakingMarker,
        T3: SpecShakingMarker,
        T4: SpecShakingMarker,
        T5: SpecShakingMarker,
        T6: SpecShakingMarker,
    > SpecShakingMarker for (T0, T1, T2, T3, T4, T5, T6)
{
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[
            T0::MARKER_NODE,
            T1::MARKER_NODE,
            T2::MARKER_NODE,
            T3::MARKER_NODE,
            T4::MARKER_NODE,
            T5::MARKER_NODE,
            T6::MARKER_NODE,
        ],
    } as *const MarkerNode;
}

impl<
        T0: SpecShakingMarker,
        T1: SpecShakingMarker,
        T2: SpecShakingMarker,
        T3: SpecShakingMarker,
        T4: SpecShakingMarker,
        T5: SpecShakingMarker,
        T6: SpecShakingMarker,
        T7: SpecShakingMarker,
    > SpecShakingMarker for (T0, T1, T2, T3, T4, T5, T6, T7)
{
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[
            T0::MARKER_NODE,
            T1::MARKER_NODE,
            T2::MARKER_NODE,
            T3::MARKER_NODE,
            T4::MARKER_NODE,
            T5::MARKER_NODE,
            T6::MARKER_NODE,
            T7::MARKER_NODE,
        ],
    } as *const MarkerNode;
}

impl<
        T0: SpecShakingMarker,
        T1: SpecShakingMarker,
        T2: SpecShakingMarker,
        T3: SpecShakingMarker,
        T4: SpecShakingMarker,
        T5: SpecShakingMarker,
        T6: SpecShakingMarker,
        T7: SpecShakingMarker,
        T8: SpecShakingMarker,
    > SpecShakingMarker for (T0, T1, T2, T3, T4, T5, T6, T7, T8)
{
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[
            T0::MARKER_NODE,
            T1::MARKER_NODE,
            T2::MARKER_NODE,
            T3::MARKER_NODE,
            T4::MARKER_NODE,
            T5::MARKER_NODE,
            T6::MARKER_NODE,
            T7::MARKER_NODE,
            T8::MARKER_NODE,
        ],
    } as *const MarkerNode;
}

impl<
        T0: SpecShakingMarker,
        T1: SpecShakingMarker,
        T2: SpecShakingMarker,
        T3: SpecShakingMarker,
        T4: SpecShakingMarker,
        T5: SpecShakingMarker,
        T6: SpecShakingMarker,
        T7: SpecShakingMarker,
        T8: SpecShakingMarker,
        T9: SpecShakingMarker,
    > SpecShakingMarker for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9)
{
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[
            T0::MARKER_NODE,
            T1::MARKER_NODE,
            T2::MARKER_NODE,
            T3::MARKER_NODE,
            T4::MARKER_NODE,
            T5::MARKER_NODE,
            T6::MARKER_NODE,
            T7::MARKER_NODE,
            T8::MARKER_NODE,
            T9::MARKER_NODE,
        ],
    } as *const MarkerNode;
}

impl<
        T0: SpecShakingMarker,
        T1: SpecShakingMarker,
        T2: SpecShakingMarker,
        T3: SpecShakingMarker,
        T4: SpecShakingMarker,
        T5: SpecShakingMarker,
        T6: SpecShakingMarker,
        T7: SpecShakingMarker,
        T8: SpecShakingMarker,
        T9: SpecShakingMarker,
        T10: SpecShakingMarker,
    > SpecShakingMarker for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)
{
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[
            T0::MARKER_NODE,
            T1::MARKER_NODE,
            T2::MARKER_NODE,
            T3::MARKER_NODE,
            T4::MARKER_NODE,
            T5::MARKER_NODE,
            T6::MARKER_NODE,
            T7::MARKER_NODE,
            T8::MARKER_NODE,
            T9::MARKER_NODE,
            T10::MARKER_NODE,
        ],
    } as *const MarkerNode;
}

impl<
        T0: SpecShakingMarker,
        T1: SpecShakingMarker,
        T2: SpecShakingMarker,
        T3: SpecShakingMarker,
        T4: SpecShakingMarker,
        T5: SpecShakingMarker,
        T6: SpecShakingMarker,
        T7: SpecShakingMarker,
        T8: SpecShakingMarker,
        T9: SpecShakingMarker,
        T10: SpecShakingMarker,
        T11: SpecShakingMarker,
    > SpecShakingMarker for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)
{
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[
            T0::MARKER_NODE,
            T1::MARKER_NODE,
            T2::MARKER_NODE,
            T3::MARKER_NODE,
            T4::MARKER_NODE,
            T5::MARKER_NODE,
            T6::MARKER_NODE,
            T7::MARKER_NODE,
            T8::MARKER_NODE,
            T9::MARKER_NODE,
            T10::MARKER_NODE,
            T11::MARKER_NODE,
        ],
    } as *const MarkerNode;
}

impl<
        T0: SpecShakingMarker,
        T1: SpecShakingMarker,
        T2: SpecShakingMarker,
        T3: SpecShakingMarker,
        T4: SpecShakingMarker,
        T5: SpecShakingMarker,
        T6: SpecShakingMarker,
        T7: SpecShakingMarker,
        T8: SpecShakingMarker,
        T9: SpecShakingMarker,
        T10: SpecShakingMarker,
        T11: SpecShakingMarker,
        T12: SpecShakingMarker,
    > SpecShakingMarker for (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)
{
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[
            T0::MARKER_NODE,
            T1::MARKER_NODE,
            T2::MARKER_NODE,
            T3::MARKER_NODE,
            T4::MARKER_NODE,
            T5::MARKER_NODE,
            T6::MARKER_NODE,
            T7::MARKER_NODE,
            T8::MARKER_NODE,
            T9::MARKER_NODE,
            T10::MARKER_NODE,
            T11::MARKER_NODE,
            T12::MARKER_NODE,
        ],
    } as *const MarkerNode;
}

// --- Built-in SDK types -----------------------------------------------------

impl SpecShakingMarker for crate::Address {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::Bytes {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl<const N: usize> SpecShakingMarker for crate::BytesN<N> {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::String {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::Symbol {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::U256 {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::I256 {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::Timepoint {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::Duration {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::Val {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::Error {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}

// SDK container types — single-child forwards directly (see Option impl above).
impl<T: SpecShakingMarker> SpecShakingMarker for crate::Vec<T> {
    const MARKER_NODE: *const MarkerNode = T::MARKER_NODE;
}

impl<K: SpecShakingMarker, V: SpecShakingMarker> SpecShakingMarker for crate::Map<K, V> {
    const MARKER_NODE: *const MarkerNode = &MarkerNode {
        marker: [0u8; 14],
        children: &[K::MARKER_NODE, V::MARKER_NODE],
    } as *const MarkerNode;
}

impl SpecShakingMarker for crate::MuxedAddress {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl<const N: usize> SpecShakingMarker for crate::crypto::Hash<N> {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::crypto::bls12_381::Bls12381G1Affine {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::crypto::bls12_381::Bls12381G2Affine {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::crypto::bls12_381::Bls12381Fp {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::crypto::bls12_381::Bls12381Fp2 {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::crypto::bls12_381::Bls12381Fr {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::crypto::bn254::Bn254G1Affine {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::crypto::bn254::Bn254G2Affine {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::crypto::bn254::Bn254Fp {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::crypto::bn254::Bn254Fr {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}

// Auth types — these have export=false but are legitimately used at external
// boundaries (as inputs to __check_auth in custom account contracts).
// They don't emit specs themselves because they're internal SDK types.
impl SpecShakingMarker for crate::auth::Context {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::auth::ContractContext {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::auth::CreateContractHostFnContext {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::auth::CreateContractWithConstructorHostFnContext {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::auth::ContractExecutable {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::auth::InvokerContractAuthEntry {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
impl SpecShakingMarker for crate::auth::SubContractInvocation {
    const MARKER_NODE: *const MarkerNode = &raw const EMPTY_MARKER_NODE;
}
