//! SpecAnchor is an internal trait used to ensure that the spec of a
//! user-defined type, error or event is linked into a contract built without
//! LTO.
//!
//! A spec entry is a static in the object file of the crate that defines the
//! type, error or event, and when a contract is built without LTO the linker
//! only includes that object file if the contract references a symbol in it.
//! The conversions generated for a type, error or event can be inlined into the
//! contract, so without a call into the defining crate the object file, and the
//! spec entry, can be left out.
//!
//! The conversions generated by the `contracttype`, `contracterror` and
//! `contractevent` macros call [`SpecAnchor::spec_anchor`], which the macros
//! implement as an empty fn that is never inlined, so that calling it
//! references a symbol in the defining crate. With LTO the calls to it are
//! optimised away.
//!
//! The fn is on a trait, rather than an inherent fn, so that it cannot clash
//! with an inherent fn of the same name on the type.

/// Trait for types, errors and events whose spec must be linked into the
/// contract.
///
/// This trait is used internally by the SDK, and types with
/// `#[contracttype]`, `#[contracterror]` or `#[contractevent]` implement it.
#[doc(hidden)]
pub trait SpecAnchor {
    /// Reference a symbol in the crate that defines the type, error or event,
    /// so that its spec entry is linked into the contract.
    fn spec_anchor();
}
