//! SpecShakingMarker is an internal trait used to ensure that an error's spec
//! is included in the WASM binary when the error is used at a point that
//! nothing in the contract spec names.
//!
//! The trait is called where a contract panics with an error, by
//! [`crate::Env::panic_with_error`], and so covers `panic_with_error!` and
//! `assert_with_error!`. An error used that way appears nowhere in the
//! contract's spec, so a marker is the only evidence it is used.
//!
//! Every other user-defined type is named by whatever references it — a
//! function's inputs and outputs, an event's params, another type's fields —
//! so post-processing tools keep or drop its spec entry by walking those
//! references, and the type needs no marker. Events are the one other
//! exception, and their marker is emitted where the event is published, by
//! code the `contractevent` macro generates.
//!
//! The trait has a default no-op implementation, so that a type usable with
//! `panic_with_error!` that carries no spec of its own, like [`crate::Error`],
//! satisfies the bound without emitting anything. Types generated by the
//! `contracterror` macro implement it to include their spec XDR in the WASM's
//! contractspecv0 section.

/// Trait for types that may include their spec in the WASM binary.
///
/// This trait is used internally by the SDK to ensure an error's spec is
/// included when the error is panicked with, which is a use of the error that
/// nothing in the contract spec names.
///
/// Types with `#[contracterror]` will have implementations that include their
/// spec. All other types have a no-op implementation.
#[doc(hidden)]
pub trait SpecShakingMarker {
    /// Include this type's spec in the WASM binary.
    ///
    /// For types that carry no spec of their own, this is a no-op. For
    /// user-defined error types, this ensures the spec XDR is included in the
    /// contractspecv0 section.
    #[inline(always)]
    fn spec_shaking_marker() {}
}

// A raw error carries no spec of its own, but is usable with
// `panic_with_error!` in place of a `#[contracterror]` type.
impl SpecShakingMarker for crate::Error {}
