//! SpecTypeDef is an internal trait that gives the contract spec type of a Rust
//! type, for spec entries that refer to types the macros cannot map by name.
//!
//! The macros map the types they recognise by name, such as `u32` or
//! `Vec<T>`, to their spec type directly. Any other type, such as a
//! user-defined type or a type alias, is referred to through this trait, so
//! that the compiler resolves the type and the spec type comes from the
//! type the name resolves to. A type alias therefore has the spec type of the
//! type it aliases.

use crate::{
    crypto::{
        bls12_381::{
            Bls12381Fp, Bls12381Fp2, Bls12381Fr, Bls12381G1Affine, Bls12381G2Affine,
            FP2_SERIALIZED_SIZE, FP_SERIALIZED_SIZE, G1_SERIALIZED_SIZE, G2_SERIALIZED_SIZE,
        },
        bn254::{
            Bn254Fp, Bn254Fr, Bn254G1Affine, Bn254G2Affine, BN254_FP_SERIALIZED_SIZE,
            BN254_G1_SERIALIZED_SIZE, BN254_G2_SERIALIZED_SIZE,
        },
    },
    xdr::r#const::{
        ScSpecTypeBytesN, ScSpecTypeDef, ScSpecTypeMap, ScSpecTypeOption, ScSpecTypeResult,
        ScSpecTypeTuple, ScSpecTypeVec, VecM,
    },
    Address, Bytes, BytesN, Duration, Error, Map, MuxedAddress, String, Symbol, Timepoint, Val,
    Vec, I256, U256,
};

/// Trait for types that have a type in the contract spec.
///
/// It is an associated const, rather than a fn, so that spec entries can be
/// built at compile time.
#[diagnostic::on_unimplemented(
    message = "`{Self}` cannot be used in a contract spec",
    label = "not a contract type",
    note = "types used in contract types, functions, and events must be supported by the contract spec, such as types marked `#[contracttype]`"
)]
pub trait SpecTypeDef {
    const SPEC_TYPE_DEF: ScSpecTypeDef;
}

/// Trait for user-defined types that have a name in the contract spec.
///
/// The name is the type's Rust path: the module it is defined in, then its own
/// name. Types generated by the contracttype, contractevent, and contracterror
/// macros implement this trait and have a [`SpecTypeDef`] that refers to the
/// type by this name.
pub trait SpecName {
    const SPEC_NAME: &'static str;
}

macro_rules! impl_spec_type_def {
    ($($t:ty => $def:expr),* $(,)?) => {
        $(
            impl SpecTypeDef for $t {
                const SPEC_TYPE_DEF: ScSpecTypeDef = $def;
            }
        )*
    };
}

impl_spec_type_def! {
    Val => ScSpecTypeDef::Val,
    bool => ScSpecTypeDef::Bool,
    () => ScSpecTypeDef::Void,
    Error => ScSpecTypeDef::Error,
    u32 => ScSpecTypeDef::U32,
    i32 => ScSpecTypeDef::I32,
    u64 => ScSpecTypeDef::U64,
    i64 => ScSpecTypeDef::I64,
    Timepoint => ScSpecTypeDef::Timepoint,
    Duration => ScSpecTypeDef::Duration,
    u128 => ScSpecTypeDef::U128,
    i128 => ScSpecTypeDef::I128,
    U256 => ScSpecTypeDef::U256,
    I256 => ScSpecTypeDef::I256,
    Bytes => ScSpecTypeDef::Bytes,
    String => ScSpecTypeDef::String,
    Symbol => ScSpecTypeDef::Symbol,
    Address => ScSpecTypeDef::Address,
    MuxedAddress => ScSpecTypeDef::MuxedAddress,
    // The BLS12-381 and BN254 types are represented in the spec by their
    // underlying data types, as the macros map them by name.
    Bls12381Fp => ScSpecTypeDef::BytesN(ScSpecTypeBytesN { n: FP_SERIALIZED_SIZE as u32 }),
    Bls12381Fp2 => ScSpecTypeDef::BytesN(ScSpecTypeBytesN { n: FP2_SERIALIZED_SIZE as u32 }),
    Bls12381G1Affine => ScSpecTypeDef::BytesN(ScSpecTypeBytesN { n: G1_SERIALIZED_SIZE as u32 }),
    Bls12381G2Affine => ScSpecTypeDef::BytesN(ScSpecTypeBytesN { n: G2_SERIALIZED_SIZE as u32 }),
    Bls12381Fr => ScSpecTypeDef::U256,
    Bn254Fp => ScSpecTypeDef::BytesN(ScSpecTypeBytesN { n: BN254_FP_SERIALIZED_SIZE as u32 }),
    Bn254G1Affine => ScSpecTypeDef::BytesN(ScSpecTypeBytesN { n: BN254_G1_SERIALIZED_SIZE as u32 }),
    Bn254G2Affine => ScSpecTypeDef::BytesN(ScSpecTypeBytesN { n: BN254_G2_SERIALIZED_SIZE as u32 }),
    Bn254Fr => ScSpecTypeDef::U256,
}

// `Hash<N>` is deliberately not implemented: the macros only accept it where
// the value is guaranteed to come from a cryptographic hash function.

impl<const N: usize> SpecTypeDef for BytesN<N> {
    const SPEC_TYPE_DEF: ScSpecTypeDef = ScSpecTypeDef::BytesN(ScSpecTypeBytesN { n: N as u32 });
}

impl<T: SpecTypeDef> SpecTypeDef for Option<T> {
    const SPEC_TYPE_DEF: ScSpecTypeDef = ScSpecTypeDef::Option(&ScSpecTypeOption {
        value_type: &T::SPEC_TYPE_DEF,
    });
}

impl<T: SpecTypeDef, E: SpecTypeDef> SpecTypeDef for Result<T, E> {
    const SPEC_TYPE_DEF: ScSpecTypeDef = ScSpecTypeDef::Result(&ScSpecTypeResult {
        ok_type: &T::SPEC_TYPE_DEF,
        error_type: &E::SPEC_TYPE_DEF,
    });
}

impl<T: SpecTypeDef> SpecTypeDef for Vec<T> {
    const SPEC_TYPE_DEF: ScSpecTypeDef = ScSpecTypeDef::Vec(&ScSpecTypeVec {
        element_type: &T::SPEC_TYPE_DEF,
    });
}

impl<K: SpecTypeDef, V: SpecTypeDef> SpecTypeDef for Map<K, V> {
    const SPEC_TYPE_DEF: ScSpecTypeDef = ScSpecTypeDef::Map(&ScSpecTypeMap {
        key_type: &K::SPEC_TYPE_DEF,
        value_type: &V::SPEC_TYPE_DEF,
    });
}

macro_rules! impl_spec_type_def_for_tuple {
    ($($t:ident),+) => {
        impl<$($t: SpecTypeDef),+> SpecTypeDef for ($($t,)+) {
            const SPEC_TYPE_DEF: ScSpecTypeDef = ScSpecTypeDef::Tuple(&ScSpecTypeTuple {
                value_types: VecM::try_from_slice_or_panic(&[$($t::SPEC_TYPE_DEF),+]),
            });
        }
    };
}

impl_spec_type_def_for_tuple!(T0);
impl_spec_type_def_for_tuple!(T0, T1);
impl_spec_type_def_for_tuple!(T0, T1, T2);
impl_spec_type_def_for_tuple!(T0, T1, T2, T3);
impl_spec_type_def_for_tuple!(T0, T1, T2, T3, T4);
impl_spec_type_def_for_tuple!(T0, T1, T2, T3, T4, T5);
impl_spec_type_def_for_tuple!(T0, T1, T2, T3, T4, T5, T6);
impl_spec_type_def_for_tuple!(T0, T1, T2, T3, T4, T5, T6, T7);
impl_spec_type_def_for_tuple!(T0, T1, T2, T3, T4, T5, T6, T7, T8);
impl_spec_type_def_for_tuple!(T0, T1, T2, T3, T4, T5, T6, T7, T8, T9);
impl_spec_type_def_for_tuple!(T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10);
impl_spec_type_def_for_tuple!(T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11);
impl_spec_type_def_for_tuple!(T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12);
