//! SpecName is an internal trait that gives the name a user-defined type is
//! known by in the contract spec.
//!
//! Types generated by the contracttype, contractevent, and contracterror macros
//! implement this trait. Spec entries that refer to a user-defined type take the
//! type's name from it, because only the type's own expansion sees the module it
//! is defined in.

/// Trait for types that have a name in the contract spec.
///
/// The name is the type's Rust path: the module it is defined in, then its own
/// name. It is an associated const, rather than a fn, so that spec entries can
/// be built at compile time.
///
/// A type alias is resolved by the compiler, and the macros only see the alias's
/// name, so a reference to an alias of a primitive or SDK type reaches a type
/// that does not implement this trait, and is reported as unsupported.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a contract type",
    label = "not a contract type",
    note = "type aliases of primitive and SDK types are not supported in contract types, functions, and events, use the aliased type directly"
)]
pub trait SpecName {
    const SPEC_NAME: &'static str;
}
