name: Docs Publish

on:
  push:
    branches: [main]
  # Also runs on pull requests so that changes to this workflow can be tested.
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/configure-pages@v5
      with:
        enablement: true
    - uses: stellar/actions/rust-cache@main
    - run: rustup install nightly
    - name: Build docs for all library crates
      env:
        RUSTDOCFLAGS: -Zunstable-options --enable-index-page
      run: make doc-only CARGO_DOC_ARGS=
    - uses: actions/upload-pages-artifact@v3
      with:
        path: target/doc

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
    - id: deploy
      uses: actions/deploy-pages@v4
