name: Test with soroban-examples

on:
  push:
    branches: [main, release/**]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}-{{ github.event_name }}
  cancel-in-progress: true

jobs:
  collect-examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        repository: stellar/soroban-examples
        ref: main
    - id: dirs
      run: |
        dirs=$(find . -type f -name 'Makefile' -mindepth 2 | xargs dirname | sed 's|^\./||' | jq -Rnc '[inputs | "\(.)"]')
        echo "dirs=$dirs" >> $GITHUB_OUTPUT
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}

  test-example:
    needs: collect-examples
    strategy:
      fail-fast: false
      matrix:
        working-directory: ${{ fromJSON(needs.collect-examples.outputs.dirs) }}
    defaults:
      run:
        working-directory: soroban-examples/${{ matrix.working-directory }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout rs-soroban-sdk
      uses: actions/checkout@v5
      with:
        path: rs-soroban-sdk

    - name: Checkout soroban-examples
      uses: actions/checkout@v5
      with:
        repository: stellar/soroban-examples
        ref: main
        path: soroban-examples

    - name: Install Rust
      run: |
        rustup update
        rustup target add wasm32v1-none

    - uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
      with:
        deno-version: v2.x

    - uses: stellar/stellar-cli@v23.1.4

    - uses: stellar/actions/rust-cache@main

    - name: Patch SDK versions
      run: |
        crates=$(cd ${{ github.workspace }}/rs-soroban-sdk && cargo metadata --format-version 1 --no-deps | jq -r '.packages[] | select(.publish != []) | .name')
        find . -name Cargo.toml | while read file; do
          echo Patching "$file" ...
          dir=$(dirname "$file")
          for crate in $crates; do
            rel_path=$(realpath --relative-to="$dir" ${{ github.workspace }}/rs-soroban-sdk/$crate)
            sed -i 's|'"$crate"' = "\([^"]*\)"|'"$crate"' = { path = "'"$rel_path"'" }|g' "$file"
            sed -i 's|'"$crate"' = {.*version = "[^"]*"\(.*\)|'"$crate"' = { path = "'"$rel_path"'" \1|g' "$file"
          done
        done

    - name: Diff
      run: git diff

    - name: Build soroban-examples
      env:
        CARGO_BUILD_RUSTFLAGS: "-A deprecated"
      run: make build

    - name: Test soroban-examples
      env:
        CARGO_BUILD_RUSTFLAGS: "-A deprecated"
      run: make test
        
    - name: Diff
      run: git add -N . && git diff HEAD
