[package]
name = "test_spec_lib_v2"
version.workspace = true
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
edition = "2021"
publish = false
rust-version.workspace = true

[lib]
path = "../spec_lib/src/lib.rs"
crate-type = ["rlib"]
doctest = false

[dependencies]
soroban-sdk = "=28.0.0"
