[package]
name = "test_spec_shaking_v2"
version.workspace = true
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
edition = "2021"
publish = false
rust-version.workspace = true

[lib]
path = "../spec_shaking_v3/src/lib.rs"
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = "=28.0.0"
test_spec_lib = {package = "test_spec_lib_v2", path = "../spec_lib_v2"}

[dev-dependencies]
stellar-xdr = {workspace = true, features = ["std"]}
soroban-spec = {path = "../../soroban-spec"}
soroban-meta = {path = "../../soroban-meta"}
