name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npx @marp-team/marp-cli@2.3.0 slides.md -o index.html
    - uses: actions/upload-pages-artifact@v1
      with:
        path: ./

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/configure-pages@v2
    - id: deployment
      uses: actions/deploy-pages@v1
